# Arrays vs Lists

In [1]:
list_two = list(range(1, 4))
list_three = list(range(1, 4))
list_sum = []

for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])

print(list_sum)

[2, 12, 36]


In [10]:
import numpy as np

array_two = np.arange(1, 4) ** 2
array_three = np.arange(1, 4) ** 3
print(array_two + array_three)

[ 2 12 36]


In [12]:
sample_array = np.array([1,2,3])

In [13]:
print(np.power(sample_array, 4))

[ 1 16 81]


In [14]:
print(np.negative(sample_array))

[-1 -2 -3]


In [15]:
print(np.exp(sample_array))

[ 2.71828183  7.3890561  20.08553692]


In [16]:
print(np.log(sample_array))

[0.         0.69314718 1.09861229]


In [17]:
print(np.sin(sample_array))

[0.84147098 0.90929743 0.14112001]


# Multidimensional Arrays

In [36]:
import numpy as np

x = np.arange(3)
y = np.arange(3, 6)
z = np.arange(6, 9)

multi_array = np.array([x, y, z]) #, dtype = np.uint8)
print(multi_array)
print(multi_array.shape)
# Access via [n, m] (row, col)
multi_array[1,2]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


5

In [37]:
# 64 bit integers
print(multi_array.dtype)

uint8


# One Dimensional Slicing

In [39]:
import numpy as np

x = np. arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [41]:
x[2:7:2]
# Start, End, Step

array([3, 5, 7])

In [42]:
# Reshaping

In [54]:
import numpy as np

x = np. arange(18).reshape(3, 2, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


# Multidimensional Slicing & Indexing

In [60]:
x[1, ...]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [61]:
x[:, 0, 0]

array([ 0,  6, 12])

In [62]:
x[1, :2, :3 :2]

array([[ 6,  8],
       [ 9, 11]])

In [65]:
x[x>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [66]:
x.max()

17

In [67]:
x.min()

0

# Manipulating Array Shapes

In [76]:
import numpy as np

x = np. arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [77]:
ravelled_array = x.ravel() # View of original array
print(ravelled_array)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [73]:
flattened_array = x.flatten() # Allocates new memory
print(flattened_array)

[0 1 2 3 4 5 6 7 8]


In [80]:
y = np.arange(9)
y.shape = [3, 3]
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [81]:
print(y.transpose())
print(y.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [82]:
print(np.resize(y, (6, 6)))
# Repeats to fill in newly added rows and columns

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [87]:
np.zeros((3, 2), dtype=int)
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [89]:
print(np.eye(3))
# Identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [91]:
np.random.rand(4,4)

array([[0.09413921, 0.18111314, 0.52632847, 0.41341653],
       [0.4689767 , 0.91939196, 0.99645942, 0.79432198],
       [0.26922859, 0.46189564, 0.73080069, 0.48691275],
       [0.02258904, 0.32125543, 0.16839369, 0.43704913]])

# Matrix Multiplication

In [92]:
import numpy as np
mat_a = np.matrix([0, 3, 5, 5, 5, 2]).reshape(2, 3)
mat_a

matrix([[0, 3, 5],
        [5, 5, 2]])

In [93]:
mat_b = np.matrix([3, 4 ,3, -2, 4, -2]).reshape(3, 2)
mat_b

matrix([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [98]:
mat_a * mat_b
product = np.matmul(mat_a, mat_b)
mat_a @ mat_b

matrix([[ 29, -16],
        [ 38,   6]])

# Stacking

In [99]:
import numpy as np

x = np.arange(4).reshape(2, 2)
print(x)

[[0 1]
 [2 3]]


In [101]:
y = np.arange(4, 8).reshape(2, 2)
print(y)

[[4 5]
 [6 7]]


In [105]:
z = np.hstack((x, y))
# Must have same shape along the first axis
print(z)

[[0 1 4 5]
 [2 3 6 7]]


In [107]:
print(z.shape)
# Concatenates along the second axis

(2, 4)


In [109]:
w = np.concatenate((x,y), axis  = 1)
# Equivalent to horizontal stacking
# Note axis starts at 0
print(w)

[[0 1 4 5]
 [2 3 6 7]]


In [110]:
print(z == w)

[[ True  True  True  True]
 [ True  True  True  True]]


In [112]:
depth_stack = np.dstack((x,y))
print(depth_stack)

[[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]


In [113]:
print(depth_stack.shape)

(2, 2, 2)


In [115]:
print(np.column_stack((x,y)) == np.hstack((x,y)))


[[ True  True  True  True]
 [ True  True  True  True]]
